/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AmazonManagement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.AmazonRequestHandlingOrganization;
import Business.Organization.BestBuyOrganization;
import Business.Organization.IkeaOrganization;
import Business.Organization.Organization;
import Business.Organization.TargetOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AmazonOrderWorkRequest;
import Business.WorkQueue.BestBuyOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishi Nandedkar
 */
public class AmazonRequestHandlingArea extends javax.swing.JPanel {

    /**
     * Creates new form AmazonRequestHandlingArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    AmazonRequestHandlingOrganization amazonRequestHandlingOrganization;
    Enterprise enterprise;
    EcoSystem business;
    Order order;
    
    public AmazonRequestHandlingArea(JPanel userProcessContainer, UserAccount account, AmazonRequestHandlingOrganization amazonRequestHandlingOrganization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.amazonRequestHandlingOrganization = amazonRequestHandlingOrganization;
        this.enterprise = enterprise;
        this.business= business;
        order = new Order();
        populateWorkQueueTable();
       // populateLowerTable();
        //refreshOrderTable();
    }

  
     public void populateWorkQueueTable(){
         DefaultTableModel model = (DefaultTableModel) amazonRequestHandlingTable.getModel();
        
        model.setRowCount(0);
        
        
        
        for (WorkRequest work : amazonRequestHandlingOrganization.getWorkQueue().getWorkRequestList()){
            if(work instanceof AmazonOrderWorkRequest){ 
            for(OrderItem oi : work.getOrder().getOrderItemList()){
               
                 Object[] row = new Object[8];
                 row[0] = oi.getCategory();
                 row[1] = oi.getProductID();
                 row[2] = oi.getProductName();
                 row[3] = oi.getQuantity();
                 row[4] = oi.getPrice() * oi.getQuantity();
                 row[5] = work.getOrder().getArea();
                 row[6] = work.getOrder().getMessage();
                 row[7] = work.toString();
            model.addRow(row);
           }
        }
    }
     }
    
    
     public void refreshOrderTable() {
        DefaultTableModel dtm = (DefaultTableModel) amazonRequestHandlingTable.getModel();
        dtm.setRowCount(0);
//for (CustomerDirectory cd: customerOrders.getCustomerDirect)
    //for(Order order : system.getOrder())
        for (Order o2 : business.getMasterOrder().getMasterOrderList()) {
            for(OrderItem oi : o2.getOrderItemList()){
            Object row[] = new Object[6];
            row[0] = oi;//.getMarketoffer().getProduct();
            row[1] = oi.getProductName();
            row[2] = oi.getPrice();
            row[3] = oi.getQuantity();
            row[4] = oi.getPrice()*oi.getQuantity();
            //row[5] = oi.getAddress();
            //row[6] = oi.getStatus();
            dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amazonRequestHandlingTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(174, 221, 221));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setText("Amazon Request Handling Work Area");

        amazonRequestHandlingTable.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        amazonRequestHandlingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Product ID", "Product Name", "Quantity", "Total Cost", "Address", "Message", "Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(amazonRequestHandlingTable);
        if (amazonRequestHandlingTable.getColumnModel().getColumnCount() > 0) {
            amazonRequestHandlingTable.getColumnModel().getColumn(0).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(1).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(2).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(3).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(4).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(5).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(6).setResizable(false);
            amazonRequestHandlingTable.getColumnModel().getColumn(7).setResizable(false);
        }

        requestTestJButton.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        requestTestJButton.setText("Assign to Retailers");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        int selectedRow = amazonRequestHandlingTable.getSelectedRow();
        String category = amazonRequestHandlingTable.getValueAt(selectedRow, 0).toString();
        int pID = Integer.parseInt(amazonRequestHandlingTable.getValueAt(selectedRow, 1).toString());
        String pName = amazonRequestHandlingTable.getValueAt(selectedRow, 2).toString();
        int quantity = Integer.parseInt(amazonRequestHandlingTable.getValueAt(selectedRow, 3).toString());
        int totalCost = Integer.parseInt(amazonRequestHandlingTable.getValueAt(selectedRow, 4).toString());
        String address = amazonRequestHandlingTable.getValueAt(selectedRow, 5).toString();
        WorkRequest work = (WorkRequest) amazonRequestHandlingTable.getValueAt(selectedRow, 7);
        String message = "Order recieved from Amazon";
         BestBuyOrderWorkRequest
                 aowr = new BestBuyOrderWorkRequest();
         
             aowr.setCategory(category);
             aowr.setProductID(pID);
             aowr.setProductName(pName);
             aowr.setQuantity(quantity);
             aowr.setPrice(totalCost);
             aowr.setArea(address);
             aowr.setMessage(message);
             aowr.setOrder(work.getOrder());
            
             
               Organization org = null;
        
        
        for (Network ntw : business.getNetworkList()){
        for (Enterprise e : ntw.getEnterpriseDirectory().getEnterpriseList())
                {
                {
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
                    { if(category.equals("Electronics")){
                        
                      if(o instanceof BestBuyOrganization){
                          
                          org = o;
                          break;
                    }
                    }
                    if(category.equals("Furniture")){
                        
                      if(o instanceof IkeaOrganization){
                          
                          org = o;
                          break;
                    }
                    }
                    if(category.equals("Clothes")){
                        
                      if(o instanceof TargetOrganization){
                          
                          org = o;
                          break;
                    }
                    }
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(aowr);
            account.getWorkQueue().getWorkRequestList().add(aowr);
        }
        }
        
//         if(category.equals("Furniture")){
//        
//        for (Network ntw : business.getNetworkList()){
//        for (Enterprise e : ntw.getEnterpriseDirectory().getEnterpriseList())
//                {
//                {
//                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
//                    {
//                        if(o instanceof IkeaOrganization){
//                          org = o;
//                          break;
//                    }
//                    }
//                }
//            }
//        }
//        if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(aowr);
//            account.getWorkQueue().getWorkRequestList().add(aowr);
//        }
//        }
//         
//          if(category.equals("Clothes")){
//        
//        for (Network ntw : business.getNetworkList()){
//        for (Enterprise e : ntw.getEnterpriseDirectory().getEnterpriseList())
//                {
//                {
//                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
//                    {
//                        if(o instanceof TargetOrganization){
//                          org = o;
//                          break;
//                    }
//                    }
//                }
//            }
//        }
//        if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(aowr);
//            account.getWorkQueue().getWorkRequestList().add(aowr);
//        }
//        }

                  JOptionPane.showMessageDialog(null, "Request sent to respective retailers");

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    
//    public void populateLowerTable(){
//    
//      DefaultTableModel model = (DefaultTableModel) amazonReadyToShipTable.getModel();
//        
//        model.setRowCount(0);
//        
//        
//        
//        for (WorkRequest work : amazonRequestHandlingOrganization.getWorkQueue().getWorkRequestList()){
//            if(work instanceof AmazonOrderWorkRequest){ 
//           // for(Order o1 : work.getOrder()){
//                    for(OrderItem oi : work.getOrder().getOrderItemList()){
//                   
//                 Object[] row = new Object[7];
//                
//                 row[0] = oi.getProductID();
//                 row[1] = oi.getProductName();
//                 row[2] = oi.getQuantity();
//                 row[3] = oi.getPrice() * oi.getQuantity();
//                
//                 row[4] = work.getOrder().getArea();
//                 
//               row [5] = work.getOrder().getMessage();
//               row [6] =work;
//            model.addRow(row);
//                
//           }
//        }
//    }
//    
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable amazonRequestHandlingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables
}
