/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BestBuyOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishi Nandedkar
 */


public class RevenueAnalysis extends javax.swing.JPanel {

    JPanel userProcessContainer;

EcoSystem business;
    /**
     * Creates new form RevenueAnalysis
     */
    public RevenueAnalysis(JPanel userProcessContainer,EcoSystem business) {
        initComponents();
        this. userProcessContainer = userProcessContainer;
        this.business = business;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalRevenueButton = new javax.swing.JButton();
        categoryRevenueBtn = new javax.swing.JButton();
        revenueAreaBtn = new javax.swing.JButton();
        revenueAreaBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(174, 221, 221));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setText("Revenue Analysis");
        add(jLabel1);
        jLabel1.setBounds(394, 38, 248, 31);

        totalRevenueButton.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        totalRevenueButton.setText("Total Revenue from all Orders >>");
        totalRevenueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRevenueButtonActionPerformed(evt);
            }
        });
        add(totalRevenueButton);
        totalRevenueButton.setBounds(350, 143, 340, 44);

        categoryRevenueBtn.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        categoryRevenueBtn.setText("Revenue by Category >>");
        categoryRevenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryRevenueBtnActionPerformed(evt);
            }
        });
        add(categoryRevenueBtn);
        categoryRevenueBtn.setBounds(350, 219, 340, 45);

        revenueAreaBtn.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        revenueAreaBtn.setText("Revenue by Area >>");
        revenueAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueAreaBtnActionPerformed(evt);
            }
        });
        add(revenueAreaBtn);
        revenueAreaBtn.setBounds(350, 300, 340, 44);

        revenueAreaBtn1.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        revenueAreaBtn1.setText("<< Back");
        revenueAreaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueAreaBtn1ActionPerformed(evt);
            }
        });
        add(revenueAreaBtn1);
        revenueAreaBtn1.setBounds(20, 751, 95, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void revenueAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueAreaBtnActionPerformed
        // TODO add your handling code here:
        RevenueArea ra = new RevenueArea(userProcessContainer, business);
        userProcessContainer.add("revenueArea", ra);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_revenueAreaBtnActionPerformed

    private void totalRevenueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRevenueButtonActionPerformed
        // TODO add your handling code here:
        TotalRevenueFromAllOrders trfao = new TotalRevenueFromAllOrders(userProcessContainer, business);
        userProcessContainer.add("TotalRevenueFromAllOrders", trfao);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_totalRevenueButtonActionPerformed

    private void categoryRevenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryRevenueBtnActionPerformed
        // TODO add your handling code here:
        RevenueCategory rc = new RevenueCategory(userProcessContainer, business);
        userProcessContainer.add("RevenueCategory", rc);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_categoryRevenueBtnActionPerformed

    private void revenueAreaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueAreaBtn1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_revenueAreaBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryRevenueBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton revenueAreaBtn;
    private javax.swing.JButton revenueAreaBtn1;
    private javax.swing.JButton totalRevenueButton;
    // End of variables declaration//GEN-END:variables
}
