/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BestBuyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.RetailerEnterprise;
import Business.Network.Network;
import Business.Organization.AmazonRequestHandlingOrganization;
import Business.Organization.BestBuyOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.AmazonRequestHandlingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AmazonOrderWorkRequest;
import Business.WorkQueue.BestBuyOrderWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishi Nandedkar
 */
public class ProductConfirmationBestBuyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductConfirmationBestBuyJPanel
     */
    JPanel userProcessContainer;
    //EcoSystem business;
    //Enterprise enterprise;
    //BestBuyOrganization bestBuyOrganization;
    //UserAccount account;
    BestBuyOrderWorkRequest request;
    public ProductConfirmationBestBuyJPanel(JPanel userProcessContainer, BestBuyOrderWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.business = business;
        //this.enterprise = enterprise;
        //this.bestBuyOrganization = bestBuySalesTeamOrganization;
        //this.account =account;
        this.request = request;
    }

   


    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(174, 221, 221));
        setLayout(null);

        requestTestJButton4.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        requestTestJButton4.setText("Confirm Order");
        requestTestJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton4ActionPerformed(evt);
            }
        });
        add(requestTestJButton4);
        requestTestJButton4.setBounds(329, 235, 189, 29);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(318, 154, 57, 17);

        messageTextField.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        add(messageTextField);
        messageTextField.setBounds(457, 144, 238, 27);

        backJButton.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(18, 748, 111, 29);

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel2.setText("BestBuy Confirmation Area");
        add(jLabel2);
        jLabel2.setBounds(330, 40, 333, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton4ActionPerformed

        
         request.getOrder().setMessage(messageTextField.getText());
        
//request.setStatus("Completed");
        
        
        
//        String message = messageTextField.getText();
//
//        BestBuyOrderWorkRequest request = new BestBuyOrderWorkRequest();
//        request.setMessage(message);
//        //request.setSender(account);
//        //request.setStatus("Product packed and ready to shipped");
//
//        Organization org = null;
//
//                    for (Network ntw : business.getNetworkList()){
//        for (Enterprise e : ntw.getEnterpriseDirectory().getEnterpriseList())
//                {
//            if (e instanceof RetailerEnterprise){
//                {
//                    for(Organization o : e.getOrganizationDirectory().getOrganizationList())
//                    {
//                        if(o instanceof BestBuyOrganization){
//                          org = o;
//                          break;
//                    }
//                    }
//                }
//            }
//            }
//            if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(request);
//            account.getWorkQueue().getWorkRequestList().add(request);
//        }
//                    }
                    
      
             JOptionPane.showMessageDialog(null, "Order processed successfully");
   
       

    }//GEN-LAST:event_requestTestJButton4ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
             //System.out.println("working back code");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BestBuyWorkAreaJPanel bbwajp = (BestBuyWorkAreaJPanel) component;
        bbwajp.populateWorkQueueTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton requestTestJButton4;
    // End of variables declaration//GEN-END:variables
}
